# Generated by Django 4.2.7 on 2023-11-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام خود را وارد نمایید', max_length=100)),
                ('lastName', models.CharField(help_text='نام خانوادگی خود را وارد نمایید', max_length=100)),
                ('nationalCode', models.IntegerField(help_text='شماره ملی خود را وارد نمایید', unique=True)),
                ('phoneNumber', models.IntegerField(help_text='شماره تلفن خود را وارد نمایید', unique=True)),
                ('fatherPhoneNumber', models.IntegerField(help_text='شماره تلفن پدر را وارد نمایید')),
                ('fatherName', models.CharField(help_text='نام پدر را وارد نمایید', max_length=100)),
                ('homePhoneNumber', models.IntegerField(help_text='شماره تلفن منزل را وارد نمایید')),
                ('dateOfBirth', models.DateField(help_text='تاریخ تولد خود را وارد نمایید')),
                ('address', models.CharField(blank=True, help_text='آدرس منزل خود را وارد نمایید', max_length=500, null=True)),
                ('image', models.ImageField(blank=True, help_text='عکس خود را وارد نمایید', null=True, upload_to='imageStudents')),
            ],
        ),
    ]
